name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
 test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        fuse-overlayfs: [v1.0.0, v1.4.0, master]
    env:
      FUSEOVERLAYFS_COMMIT: "${{ matrix.fuse-overlayfs }}"
    steps:
    - uses: actions/checkout@master
    - run: make test
 cross:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@master
    - run: make artifacts
